### ISSUE TITLE
error when init ckpt,raise NotImplementedError

### ISSUE THREAD

**Issue by aigcun** [chaojie/ComfyUI-MotionCtrl-SVD#11]
FETCH DATA from: D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
#read_workflow_json_files_all D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes-main\app\
got prompt
Loading model from D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\motionctrl\motionctrl.pth
Using device cuda
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\nodes.py", line 152, in load_checkpoint
    model = build_model(config_path, ckpt_path, device, frame_length, steps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\gradio_utils\motionctrl_cmcm_gradio.py", line 55, in build_model
    model, filter = load_model(
                    ^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\gradio_utils\motionctrl_cmcm_gradio.py", line 279, in load_model
    model = instantiate_from_config(config.model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\sgm\motionctrl\camera_motion_control.py", line 63, in __init__
    self.init_from_ckpt(ckpt_path)
  File "D:\Git\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\sgm\models\diffusion.py", line 99, in init_from_ckpt
    raise NotImplementedError
NotImplementedError

Prompt executed in 21.31 seconds

**Comment by ShylockGao** [comment]
How was it solved?
