### ISSUE TITLE
AttributeError: 'NewCls' object has no attribute 'timesteps'

### ISSUE THREAD

**Issue by DorotaLuna** [chaojie/ComfyUI-MotionCtrl-SVD#2]
Just clicked queue prompt, 

Python 310, Win11, torch212+cu121

heres the log

> got prompt
Loading model from C:\AI\ComfyUI\models\checkpoints\motionctrl_svd.ckpt
Using device cuda
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Restored from C:\AI\ComfyUI\models\checkpoints\motionctrl_svd.ckpt with 0 missing and 0 unexpected keys
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\nodes.py", line 181, in run_inference
    return motionctrl_sample(
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\gradio_utils\motionctrl_cmcm_gradio.py", line 185, in motionctrl_sample
    samples_x = model.decode_first_stage(samples_z)
  File "C:\AI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI\python_embeded\lib\site-packages\sgm\models\diffusion.py", line 130, in decode_first_stage
    out = self.first_stage_model.decode(
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\sgm\models\autoencoder.py", line 211, in decode
    x = self.decoder(z, **kwargs)
  File "C:\AI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\python_embeded\lib\site-packages\sgm\modules\diffusionmodules\model.py", line 726, in forward
    h = self.mid.block_1(h, temb, **kwargs)
  File "C:\AI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MotionCtrl-SVD\sgm\modules\autoencoding\temporal_ae.py", line 66, in forward
    timesteps = self.timesteps
  File "C:\AI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'NewCls' object has no attribute 'timesteps'
Prompt executed in 58.97 seconds

**Comment by zhaowtVincent** [comment]
same error,Have you solved this problem?

**Comment by shineway14** [comment]
same error,Have you solved this problem?

**Comment by switchzts** [comment]
same error,Have you solved this problem?
