### ISSUE TITLE
Loading this custom node breaks comfyui-reactor-node

### ISSUE THREAD

**Issue by elkay** [chaojie/ComfyUI-MotionCtrl-SVD#6]
Not sure how or why, but if I load this custom node successfully it causes comfyui-reactor-node (the one installed directly from Manager) to fail to load with the following error. Note that ComfyUI-MotionCtrl-SVD does still load successfully. If I temporarily remove this custom node from the custom_nodes folder then Reactor starts loading again correctly.

-------

Traceback (most recent call last):
  File "G:\AI-Content\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI-Content\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\AI-Content\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
ModuleNotFoundError: No module named 'scripts.reactor_faceswap'

Cannot import G:\AI-Content\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'scripts.reactor_faceswap'

**Comment by cardenluo** [comment]
me too ,Have you found a way?
